# ---------------------------------
# Posts API
# ---------------------------------

# 1. Create a New Post
POST http://localhost:3000/post/createPost
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "sender": "Osher"
}

###
# 2. Get All Posts
GET http://localhost:3000/post/getAllPosts

###
# 3. Get a Post by ID
GET http://localhost:3000/post/675857f5f0dd49af4d25bbc6

###
# 4. Get Posts by Sender
GET http://localhost:3000/post?sender=Osher

###
# 5. Update a Post
PUT http://localhost:3000/post/675857f5f0dd49af4d25bbc6
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content for the post."
}

### 

# --------------------------------- 
# Comments API 
# ---------------------------------

# 1. Add a Comment to a Post 
POST http://localhost:3000/comment/createComment 
Content-Type: application/json

{
"postId": "67585ccd2177f17c0d17b602", "content": "This is a comment on the post.", "sender": "Alik"
}

### 
# 2. Get a Comment by Sender 
GET http://localhost:3000/comment/bySender?sender=Alik

###

### 
# 3. Get a Comment by ID 
GET http://localhost:3000/comment/byId/67585d072177f17c0d17b604

### 
# 4. Get All Comments for a Specific Post
GET http://localhost:3000/comment/post/67585d072177f17c0d17b604

### 
# 5. Update a Comment 
PUT http://localhost:3000/comment/update/67585d072177f17c0d17b604 
Content-Type: application/json

{
"content": "Updated comment content."
}

### 
# 6. Delete a Comment 
DELETE http://localhost:3000/comment/delete/67585d072177f17c0d17b604